---
title: "Bayes Hierarchical Models"
author: "Nicholas Di, Nolan Meyer, and Duc Ngo"
description: | 
  Using Bayes Methods to predict future earnings!
preview: https://wealthface.com/blog/wp-content/uploads/2021/05/SP500.jpg
date: 12-11-2021
output:
  distill::distill_article:
    self_contained: false
---
**Project**

Welcome to our STAT 454: Bayesian Statistics capstone project. All of us group members have an interest in and connections to the financial world, whether that be through our majors or internships, which led us toward this topic. Financial information, like stock market prices, are known to be notoriously hard to predict. We wanted to take a Bayesian approach to try and tackle a similar situation: predicting the future earnings of S&P 500 companies. In this project we seek to model future earnings using other financial information about a company, like previous earnings and sales. We explore a few Bayesian hierarchical models, as well as a SARIMA model using the bayesforcast package to try and identify one that can provide insight and better predictions for future company’s earnings.

[Project Link]( https://nolan-meyer.github.io/bayesian-finance/)